// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSzRSHTjc-6ljVrLGORIzCIKLElh64Syc',
    appId: '1:536807786520:web:2ff0d7c928029b7f341b6d',
    messagingSenderId: '536807786520',
    projectId: 'bg-location-5914655',
    authDomain: 'bg-location-5914655.firebaseapp.com',
    storageBucket: 'bg-location-5914655.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJZH-IQu0fiF6F13v1TDO4HvUmAAOYq1w',
    appId: '1:536807786520:android:047c57ad91057286341b6d',
    messagingSenderId: '536807786520',
    projectId: 'bg-location-5914655',
    storageBucket: 'bg-location-5914655.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_jV1mMop1_pTPSZZ3F3ZEZS_m9F4Id18',
    appId: '1:536807786520:ios:f8acd9c98c1d35f8341b6d',
    messagingSenderId: '536807786520',
    projectId: 'bg-location-5914655',
    storageBucket: 'bg-location-5914655.appspot.com',
    iosClientId: '536807786520-jbvehj1417qsmbjp3699s5nrg1vc4sdb.apps.googleusercontent.com',
    iosBundleId: 'com.example.example01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_jV1mMop1_pTPSZZ3F3ZEZS_m9F4Id18',
    appId: '1:536807786520:ios:f8acd9c98c1d35f8341b6d',
    messagingSenderId: '536807786520',
    projectId: 'bg-location-5914655',
    storageBucket: 'bg-location-5914655.appspot.com',
    iosClientId: '536807786520-jbvehj1417qsmbjp3699s5nrg1vc4sdb.apps.googleusercontent.com',
    iosBundleId: 'com.example.example01',
  );
}
